http:
  middlewares:

    secure-headers:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
          server: ""
          X-Powered-By: ""

    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1s

    ip-allowlist:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"

    auth:
      basicAuth:
        users:
          - "admin:$2b$12$UInn9TbqOYQOzsGaUmZIRen10gzY2XB4EPLfYooweNCHzDlvwHUUq"
